import type { Task, TimeBlock } from "./types";

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    title: "Chase overdue invoice",
    client: "Gamma Inc",
    bucket: "now",
    durationMin: 15,
    dueAt: "10:00",
    priority: 1,
    type: "admin",
    status: "open",
    tags: ["Urgent"],
    blockers: [],
    source: "manual",
    whyNow: "6 days overdue — $3,200 at risk",
  },
  {
    id: "t2",
    title: "Approve ad creatives",
    client: "Beta Labs",
    bucket: "now",
    durationMin: 20,
    priority: 1,
    type: "creative",
    status: "open",
    tags: ["Urgent", "Waiting"],
    blockers: ["Client waiting 2 days"],
    source: "whatsapp",
    whyNow: "Campaign launch blocked until approved",
  },
  {
    id: "t3",
    title: "Produce content batch (3 posts)",
    client: "Gamma Inc",
    bucket: "next",
    durationMin: 90,
    priority: 2,
    type: "deep",
    status: "open",
    tags: ["Creative"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t4",
    title: "Send monthly report",
    client: "Acme Corp",
    bucket: "next",
    durationMin: 30,
    dueAt: "14:00",
    priority: 2,
    type: "admin",
    status: "open",
    tags: ["Admin"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t5",
    title: "Call client — renewal discussion",
    client: "Epsilon Studio",
    bucket: "next",
    durationMin: 25,
    dueAt: "15:30",
    priority: 3,
    type: "call",
    status: "open",
    tags: [],
    blockers: [],
    source: "manual",
  },
  {
    id: "t6",
    title: "Fix hero section on landing page",
    client: "Delta Agency",
    bucket: "next",
    durationMin: 60,
    priority: 3,
    type: "deep",
    status: "open",
    tags: ["Creative"],
    blockers: ["Waiting on hero assets from designer"],
    source: "manual",
  },
  {
    id: "t7",
    title: "Launch retargeting campaign",
    client: "Beta Labs",
    bucket: "later",
    durationMin: 45,
    priority: 4,
    type: "deep",
    status: "open",
    tags: [],
    blockers: [],
    source: "manual",
  },
  {
    id: "t8",
    title: "Review ad spend report",
    client: "Acme Corp",
    bucket: "later",
    durationMin: 20,
    priority: 4,
    type: "admin",
    status: "open",
    tags: ["Admin"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t9",
    title: "Respond to FAQ update request",
    client: "Epsilon Studio",
    bucket: "inbox",
    durationMin: 15,
    priority: 5,
    type: "admin",
    status: "open",
    tags: [],
    blockers: [],
    source: "whatsapp",
  },
  {
    id: "t10",
    title: "New project brief — social rebrand",
    client: "NewCo",
    bucket: "inbox",
    durationMin: 0,
    priority: 5,
    type: "creative",
    status: "open",
    tags: [],
    blockers: [],
    source: "email",
  },
];

export const DEFAULT_TIME_BLOCKS: TimeBlock[] = [
  { id: "tb1", label: "Morning Deep Work", minutes: 90, assignedTaskIds: [] },
  { id: "tb2", label: "Midday", minutes: 60, assignedTaskIds: [] },
  { id: "tb3", label: "Afternoon Deep Work", minutes: 90, assignedTaskIds: [] },
  { id: "tb4", label: "Admin Sweep", minutes: 45, assignedTaskIds: [] },
  { id: "tb5", label: "Buffer", minutes: 30, assignedTaskIds: [] },
];
