import type { Task, TimeBlock } from "./types";

export const SEED_TASKS: Task[] = [
  {
    id: "t1",
    title: "Chase overdue retainer",
    client: "Ardan Med Spa",
    bucket: "now",
    durationMin: 15,
    dueAt: "10:00",
    priority: 1,
    type: "admin",
    status: "open",
    tags: ["Urgent"],
    blockers: [],
    source: "manual",
    whyNow: "6 days overdue — $1,300 at risk",
  },
  {
    id: "t2",
    title: "Approve ad creatives",
    client: "The Shape SPA Miami",
    bucket: "now",
    durationMin: 20,
    priority: 1,
    type: "creative",
    status: "open",
    tags: ["Urgent", "Waiting"],
    blockers: ["Grace waiting 2 days"],
    source: "whatsapp",
    whyNow: "Body sculpting campaign launch blocked",
  },
  {
    id: "t3",
    title: "Produce content batch (4 posts)",
    client: "Casa Nova",
    bucket: "next",
    durationMin: 90,
    priority: 2,
    type: "deep",
    status: "open",
    tags: ["Creative"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t4",
    title: "Send monthly report",
    client: "Super Crisp",
    bucket: "next",
    durationMin: 30,
    dueAt: "14:00",
    priority: 2,
    type: "admin",
    status: "open",
    tags: ["Admin"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t5",
    title: "Content strategy call",
    client: "Pro Fortuna",
    bucket: "next",
    durationMin: 25,
    dueAt: "15:30",
    priority: 3,
    type: "call",
    status: "open",
    tags: [],
    blockers: [],
    source: "manual",
  },
  {
    id: "t6",
    title: "Fix hero section on website",
    client: "This is it Brazil",
    bucket: "next",
    durationMin: 60,
    priority: 3,
    type: "deep",
    status: "open",
    tags: ["Creative"],
    blockers: ["Waiting on product images from Julianna"],
    source: "manual",
  },
  {
    id: "t7",
    title: "Launch retargeting campaign",
    client: "The Shape Spa FLL",
    bucket: "later",
    durationMin: 45,
    priority: 4,
    type: "deep",
    status: "open",
    tags: [],
    blockers: [],
    source: "manual",
  },
  {
    id: "t8",
    title: "Review ad spend report",
    client: "Super Crisp",
    bucket: "later",
    durationMin: 20,
    priority: 4,
    type: "admin",
    status: "open",
    tags: ["Admin"],
    blockers: [],
    source: "manual",
  },
  {
    id: "t9",
    title: "Update service menu on website",
    client: "Hafiza",
    bucket: "inbox",
    durationMin: 15,
    priority: 5,
    type: "admin",
    status: "open",
    tags: [],
    blockers: [],
    source: "whatsapp",
  },
  {
    id: "t10",
    title: "Reels content plan for March",
    client: "Cristiane Amorim",
    bucket: "inbox",
    durationMin: 0,
    priority: 5,
    type: "creative",
    status: "open",
    tags: [],
    blockers: [],
    source: "manual",
  },
];

export const DEFAULT_TIME_BLOCKS: TimeBlock[] = [
  { id: "tb1", label: "Morning Deep Work", minutes: 90, assignedTaskIds: [] },
  { id: "tb2", label: "Midday", minutes: 60, assignedTaskIds: [] },
  { id: "tb3", label: "Afternoon Deep Work", minutes: 90, assignedTaskIds: [] },
  { id: "tb4", label: "Admin Sweep", minutes: 45, assignedTaskIds: [] },
  { id: "tb5", label: "Buffer", minutes: 30, assignedTaskIds: [] },
];
